# Generated by Django 4.2.27 on 2025-12-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=500)),
                ('cover', models.ImageField(blank=True, upload_to='covers/')),
                ('pages', models.IntegerField()),
                ('year', models.IntegerField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
